In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import nltk

In [2]:
from nltk.tokenize import word_tokenize

In [3]:
data = 'E:/Kaggle/Tweets NLP/train.csv'

In [4]:
data_test = 'E:/Kaggle/Tweets NLP/test.csv'

In [5]:
df = pd.read_csv(data)
df_test = pd.read_csv(data_test)

In [6]:
df.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [7]:
df.isnull().sum()/df.shape[0]

id          0.000000
keyword     0.008013
location    0.332720
text        0.000000
target      0.000000
dtype: float64

In [8]:
df.dtypes

id           int64
keyword     object
location    object
text        object
target       int64
dtype: object

In [9]:
df['keyword'].fillna('None',inplace=True)

In [10]:
df['location'].fillna('None',inplace=True)

In [11]:
df['text'] = df['text'].astype(str) + df['location'] + df['keyword']

In [12]:
df['text'][:1]

0    Our Deeds are the Reason of this #earthquake M...
Name: text, dtype: object

In [13]:
df.shape

(7613, 5)

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
import re

df['text'] = df['text'].map(lambda x: x.lower())

In [16]:
df['text'] = df['text'].map(lambda x:re.sub(r"http\S+", "", x))

In [17]:
df['text'] = df['text'].map(lambda x:re.sub(r"[0-9]", "", x))

In [18]:
df['text']

0       Our Deeds are the Reason of this #earthquake M...
1          Forest fire near La Ronge Sask. CanadaNoneNone
2       All residents asked to 'shelter in place' are ...
3       , people receive #wildfires evacuation orders ...
4       Just got sent this photo from Ruby #Alaska as ...
                              ...                        
7608    Two giant cranes holding a bridge collapse int...
7609    @aria_ahrary @TheTawniest The out of control w...
7610                  M. [: UTC]?km S of Volcano Hawaii. 
7611    Police investigating after an e-bike collided ...
7612    The Latest: More Homes Razed by Northern Calif...
Name: text, Length: 7613, dtype: object

# Lemmitize

In [154]:
from nltk.stem import WordNetLemmatizer 

In [155]:
lemmatizer = WordNetLemmatizer() 

In [162]:
lem_x= lemmatizer.lemmatize(lem)

In [161]:
lem = str(cv.get_feature_names())

In [163]:
lem_x

"['__', '__ohhmyjoshh', '_animaladvocate', '_ashj', '_charleyisqueen', '_dangdaddy', '_dangerousbeans', '_dc', '_dmerida', '_doofus_', '_edvinnn', '_freemarketeer', '_gaabyx', '_itsdanie_', '_itsmegss_', '_itzsteven', '_keits', '_minimehh', '_ohhsehuns', '_oliviaann_', '_one', '_reddevillife_', '_rosewell', '_stiiilo', '_wildfire__', 'a__cee', 'aa', 'aaaa', 'aaaaaand', 'aaarrrgghhh', 'aace_org', 'aamerica', 'aannnnd', 'aar', 'aashiqui', 'ab', 'aba', 'abablaze', 'abandon', 'abandoned', 'abandonedpics', 'abandoning', 'abbandoned', 'abbott', 'abbruchsimulator', 'abbswinston', 'abc', 'abcnews', 'abcnonebioterrorism', 'abcnorio', 'abdisaster', 'abe', 'abemergency', 'aberdeen', 'aberdeenshirefirst', 'abha', 'abhail', 'abhailstorm', 'abia', 'ability', 'ablaze', 'ablazenoneablaze', 'ablazephiladelphia', 'able', 'ableg', 'abninfvet', 'abomb', 'abomination', 'abortion', 'abortions', 'abouts', 'abq', 'abran_caballero', 'abs', 'absecon', 'absence', 'absolut_sumyaindiacollapse', 'absolute', 'absolu

# Stemming

In [86]:
from nltk.stem import PorterStemmer

In [87]:
ps = PorterStemmer()

In [91]:
x

0       Our Deeds are the Reason of this #earthquake M...
1          Forest fire near La Ronge Sask. CanadaNoneNone
2       All residents asked to 'shelter in place' are ...
3       , people receive #wildfires evacuation orders ...
4       Just got sent this photo from Ruby #Alaska as ...
                              ...                        
7608    Two giant cranes holding a bridge collapse int...
7609    @aria_ahrary @TheTawniest The out of control w...
7610                  M. [: UTC]?km S of Volcano Hawaii. 
7611    Police investigating after an e-bike collided ...
7612    The Latest: More Homes Razed by Northern Calif...
Name: text, Length: 7613, dtype: object

# Continue

In [19]:
x = df['text']
y = df['target']

In [20]:
xtrain,xtest,ytrain,ytest= train_test_split(x,y,test_size=0.3, random_state=123)

In [21]:
cv = CountVectorizer(stop_words='english')

In [22]:
train = cv.fit_transform(xtrain.values)

In [23]:
cv.get_feature_names()

['__',
 '__ohhmyjoshh',
 '_animaladvocate',
 '_ashj',
 '_charleyisqueen',
 '_dangdaddy',
 '_dangerousbeans',
 '_dc',
 '_dmerida',
 '_doofus_',
 '_edvinnn',
 '_freemarketeer',
 '_gaabyx',
 '_itsdanie_',
 '_itsmegss_',
 '_itzsteven',
 '_keits',
 '_minimehh',
 '_ohhsehuns',
 '_oliviaann_',
 '_one',
 '_reddevillife_',
 '_rosewell',
 '_stiiilo',
 '_wildfire__',
 'a__cee',
 'aa',
 'aaaa',
 'aaaaaand',
 'aaarrrgghhh',
 'aace_org',
 'aamerica',
 'aannnnd',
 'aar',
 'aashiqui',
 'ab',
 'aba',
 'abablaze',
 'abandon',
 'abandoned',
 'abandonedpics',
 'abandoning',
 'abbandoned',
 'abbott',
 'abbruchsimulator',
 'abbswinston',
 'abc',
 'abcnews',
 'abcnonebioterrorism',
 'abcnorio',
 'abdisaster',
 'abe',
 'abemergency',
 'aberdeen',
 'abha',
 'abhail',
 'abhailstorm',
 'abia',
 'ability',
 'ablaze',
 'ablazenoneablaze',
 'ablazephiladelphia',
 'able',
 'ableg',
 'abninfvet',
 'abomb',
 'abomination',
 'abortion',
 'abortions',
 'abouts',
 'abq',
 'abran_caballero',
 'abs',
 'absence',
 'absolut_

In [24]:
test = cv.transform(xtest.values)

# Scores UDF

In [62]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [72]:
def scores(x,y):
    print(accuracy_score(x,y)) 

    print(confusion_matrix(x,y))

# Naive Bayes

In [31]:
from sklearn.naive_bayes import MultinomialNB

In [171]:
nb_classifier = MultinomialNB(alpha=1.2)

In [172]:
nb_classifier.fit(train,ytrain)

MultinomialNB(alpha=1.2, class_prior=None, fit_prior=True)

In [173]:
pred = nb_classifier.predict(test)

In [174]:
accuracy_score(ytest,pred)

0.7915936952714536

In [175]:
confusion_matrix(ytest,pred)

array([[1087,  226],
       [ 250,  721]], dtype=int64)

# Random Forest

In [133]:
from sklearn.ensemble import RandomForestClassifier

In [134]:
rf = RandomForestClassifier(n_estimators = 150)

In [135]:
rf.fit(train,ytrain)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=150, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [136]:
pred_rf = rf.predict(test)

In [137]:
accuracy_score(ytest,pred_rf)

0.7876532399299475

# Tpot Classifier

In [138]:
from tpot import TPOTClassifier

In [95]:
tpot = TPOTClassifier(generations = 5, population_size=5,verbosity=2, offspring_size = 3, scoring = 'accuracy', 
                     cv=3,early_stop = 3, random_state = 12, config_dict = 'TPOT sparse' )

In [96]:
tpot.fit(train,ytrain)

Generation 1 - Current best internal CV score: 0.7894587332662265
Generation 2 - Current best internal CV score: 0.7894587332662265

The optimized pipeline was not improved after evaluating 3 more generations. Will end the optimization process.

TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: LogisticRegression(input_matrix, C=0.5, dual=False, penalty=l2)


TPOTClassifier(config_dict='TPOT sparse', crossover_rate=0.1, cv=3,
        disable_update_check=False, early_stop=3, generations=5,
        max_eval_time_mins=5, max_time_mins=None, memory=None,
        mutation_rate=0.9, n_jobs=1, offspring_size=3,
        periodic_checkpoint_folder=None, population_size=5,
        random_state=12, scoring='accuracy', subsample=1.0,
        template='RandomTree', use_dask=False, verbosity=2,
        warm_start=False)

In [129]:
pred_tpot = tpot.predict(test)

In [130]:
accuracy_score(ytest,pred_tpot)

0.8069176882661997

In [273]:
confusion_matrix(ytest,pred_tpot)

array([[1178,  135],
       [ 306,  665]], dtype=int64)

# Logistic Regression

In [25]:
from sklearn.linear_model import LogisticRegression

In [52]:
lr = LogisticRegression(penalty='l2', solver='sag')

In [53]:
model_lr = lr.fit(train,ytrain)

C:\Users\Pradeep\Anaconda3\lib\site-packages\sklearn\linear_model\sag.py:334: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


In [54]:
predict_lr = model_lr.predict(test)

In [55]:
accuracy_score(ytest,predict_lr)

0.792907180385289

In [56]:
confusion_matrix(ytest,predict_lr)

array([[1142,  171],
       [ 302,  669]], dtype=int64)

# XGBoost

In [57]:
from xgboost import XGBClassifier

In [82]:
xgb = XGBClassifier(n_estimators=3000, max_depth=4, n_jobs=-1)

In [83]:
model_xgb= xgb.fit(train,ytrain)

In [84]:
predict_xgb = model_xgb.predict(test)

In [85]:
scores(ytest,predict_xgb)

0.7692644483362522
[[1073  240]
 [ 287  684]]


# Test Data Prediction

In [84]:
test_text = df_test['text']

In [85]:
test_text

0                      Just happened a terrible car crash
1       Heard about #earthquake is different cities, s...
2       there is a forest fire at spot pond, geese are...
3                Apocalypse lighting. #Spokane #wildfires
4           Typhoon Soudelor kills 28 in China and Taiwan
                              ...                        
3258    EARTHQUAKE SAFETY LOS ANGELES ‰ÛÒ SAFETY FASTE...
3259    Storm in RI worse than last hurricane. My city...
3260    Green Line derailment in Chicago http://t.co/U...
3261    MEG issues Hazardous Weather Outlook (HWO) htt...
3262    #CityofCalgary has activated its Municipal Eme...
Name: text, Length: 3263, dtype: object

In [86]:
test_cv = cv.transform(test_text.values)

In [87]:
test_predict= nb_classifier.predict(test_cv)

In [88]:
test_predict

array([0, 1, 1, ..., 1, 1, 1], dtype=int64)

In [89]:
submission = pd.DataFrame({'id':df_test['id'],'target':test_predict})

In [90]:
submission.to_csv('Tweet_2.csv', index=False)